version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  test:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test
  lint:
    docker:
      - image: cimg/node:14.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run lint
          command: yarn lint

workflows:
  sample:
    jobs:
      - test
      - lint
